### ISSUE TITLE
Add api registration based on service meta

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/api-registrator#1]
We can use service tags in order to decide
-should a service be registered yes/no
-what api routes should be registered
Tags: 
kong - this will register the service under its serviceName, e.g. kongHost:kongPort/<serviceName>/* will be routed to service

kong_<sourcePath>_<pathToMap> - could allow more customization, e.g.
kong_/register_/user/register (idea for later, skip in scope of this card)

**Comment by sureshvarman-cronj** [comment]
right now the dev environment service doesn't have tags as kong, other than supplier service, so will wait until dev has change, this will be small change, since we have filter already based on name
